### ISSUE TITLE
stopped working in 1.8

### ISSUE THREAD

**Issue by devel1988** [DMagic1/KSP_Science_Relay#7]
KSP_SR stopped working in 1.8, anything i can do to debug it ?

**Comment by asdfCYBER** [comment]
If you're lucky, all it takes is a recompile with the KSP 1.8 DLLs and .NET 4.x

**Comment by DMagic1** [comment]
Unfortunately that won't work in this case. The current version doesn't work at all in 1.8 without some pretty significant changes. 

A release should be up tomorrow, it just needs some more testing.

**Comment by devel1988** [comment]
always willing to help out with testing, i have a C# programming background. i've got the repo in my Visual studio atm, and am able to compile

**Comment by DMagic1** [comment]
Should be working now.
